export { HeroSection } from './HeroSection';
export { SocialProofSection } from './SocialProofSection';
export { HowItWorksSection } from './HowItWorksSection';
export { CourseLevelsSection } from './CourseLevelsSection';
export { WhatYouGetSection } from './WhatYouGetSection';
export { InstructorSection } from './InstructorSection';
export { PricingSection } from './PricingSection';
export { CohortUrgencySection } from './CohortUrgencySection';
export { FinalCTASection } from './FinalCTASection';
